### ISSUE TITLE
Please add following line to .bashrc: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/jayking/.mujoco/mujoco210/bin

### ISSUE THREAD

**Issue by HappyJayLiu** [dmksjfl/DARC#1]
Exception: 
Missing path to your environment variable. 
Current values LD_LIBRARY_PATH=
Please add following line to .bashrc:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/jayking/.mujoco/mujoco210/bin

![2024-03-22 21-04-16 的屏幕截图](https://github.com/dmksjfl/DARC/assets/104080593/d7e0fe3d-ace2-4247-8bb1-77b908fd3c7a)

I've added the path, but there is still a bug, and the fix has not been successful after a day, is there a solution?

**Comment by dmksjfl** [comment]
Hi, that does not seem to be a issue for this repo itself. It seems you do not export the path of mujoco. Please try following the recommendation, and remenber to `source ~/.bashrc` after modification to make it work.

**Comment by dmksjfl** [comment]
Hi, since this issue does not seem a bug for this repo, I am closing this issue now.
